"""use json for affected_systems and audit log values

Revision ID: 654f6b222266
Revises: 2023a426650c
Create Date: 2026-03-28 09:50:35.857023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '654f6b222266'
down_revision: Union[str, Sequence[str], None] = '2023a426650c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual fix: PostgreSQL needs explicit USING clause for type conversion
    op.execute("ALTER TABLE audit_log ALTER COLUMN old_value TYPE JSON USING old_value::json")
    op.execute("ALTER TABLE audit_log ALTER COLUMN new_value TYPE JSON USING new_value::json")
    op.execute("ALTER TABLE tickets ALTER COLUMN affected_systems TYPE JSON USING to_jsonb(affected_systems)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual fix: PostgreSQL needs explicit USING clause for type conversion
    op.execute("ALTER TABLE tickets ALTER COLUMN affected_systems TYPE VARCHAR[] USING ARRAY(SELECT jsonb_array_elements_text(affected_systems::jsonb))")
    op.execute("ALTER TABLE audit_log ALTER COLUMN new_value TYPE JSONB USING new_value::jsonb")
    op.execute("ALTER TABLE audit_log ALTER COLUMN old_value TYPE JSONB USING old_value::jsonb")
    # ### end Alembic commands ###
