"""add stage column to tickets

Revision ID: 98aebda2f8c9
Revises: 01c64b169b85
Create Date: 2026-04-12 07:03:02.624853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98aebda2f8c9'
down_revision: Union[str, Sequence[str], None] = '01c64b169b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('stage', sa.String(length=20), nullable=False, server_default='unknown'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'stage')
    # ### end Alembic commands ###
