"""add skills column to tickets

Revision ID: abea5d009d13
Revises: 6fe8bc2160ac
Create Date: 2026-03-28 13:08:02.508329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abea5d009d13'
down_revision: Union[str, Sequence[str], None] = '6fe8bc2160ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('tickets', sa.Column('skills', sa.JSON(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE tickets SET skills = '[]'::json WHERE skills IS NULL")
    # Make it non-nullable
    op.alter_column('tickets', 'skills', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'skills')
    # ### end Alembic commands ###
