# Enable vi mode
setw -g mode-keys vi

# Enable mouse support
set -g mouse on

# Start selection with 'v' and copy with 'y'
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Copy to system clipboard (Linux with xclip)
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Paste from system clipboard
bind ] run "xclip -out -selection clipboard | tmux load-buffer - && tmux paste-buffer"

unbind-key -T root MouseDown3Pane
