apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kira.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kira.componentLabels" (dict "component" "frontend" "root" .) | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "kira.selectorLabels" (dict "component" "frontend" "root" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kira.componentLabels" (dict "component" "frontend" "root" .) | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kira.componentLabels" (dict "component" "frontend" "root" .) | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "kira.selectorLabels" (dict "component" "frontend" "root" .) | nindent 4 }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      {{- if eq .Values.frontend.service.type "NodePort" }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
      protocol: TCP
