{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "kira.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kira.componentLabels" (dict "component" "frontend" "root" .) | nindent 4 }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  to:
    kind: Service
    name: frontend
    weight: 100
  port:
    targetPort: {{ .Values.frontend.port }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
