apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kira.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kira.labels" . | nindent 4 }}
type: Opaque
stringData:
  KIRA_API_KEY: {{ .Values.kira.apiKey | quote }}
  KIRA_SECRET_KEY: {{ .Values.kira.secretKey | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password | quote }}
